// Author: Prateek Dhall — World Dataset Assignment.
const { test, expect } = require('@playwright/test');
const questions = require('../app/data/questions.json');
function solution(q){return q.id===30?'CREATE VIEW country_summary AS '+q.reference_sql:q.reference_sql}
async function query(request,path,q,sql,testcase='world'){return request.post('/api/'+path,{data:{question_id:q.id,sql,testcase}})}
test('official dataset, question metadata and full schema',async({request})=>{const h=await request.get('/api/health');expect(await h.json()).toEqual({ok:true,country:239,city:4079,countrylanguage:984});const qs=await (await request.get('/api/questions')).json();expect(qs).toHaveLength(30);expect(qs.map(q=>q.id)).toEqual(Array.from({length:30},(_,i)=>i+1));expect(qs.every(q=>!('reference_sql' in q)&&q.notes.length&&q.starter_sql)).toBe(true);const schema=await (await request.get('/api/schema')).json();expect(schema.country).toHaveLength(15);expect(schema.city).toHaveLength(5);expect(schema.countrylanguage).toHaveLength(4);expect(schema.country.find(c=>c.name==='Capital').nullable).toBe(true)});
for(const q of questions){test(`Q${q.id}: run, example, acceptance and wrong-answer detection`,async({request})=>{const sql=solution(q);const run=await query(request,'run',q,sql);expect(run.ok(),await run.text()).toBe(true);const data=await run.json();expect(data).toMatchObject({accepted:true,message:'Accepted',passed:1,total:1});expect(data.columns).toEqual(q.return_columns);const example=await (await request.get(`/api/questions/${q.id}/example`)).json();const sample=await (await query(request,'run',q,sql,'example')).json();expect(sample.rows).toEqual(example.rows);expect(sample.columns).toEqual(example.columns);const submit=await query(request,'submit',q,sql);expect(submit.ok(),await submit.text()).toBe(true);expect(await submit.json()).toMatchObject({accepted:true,passed:3,total:3});const empty=`SELECT ${q.return_columns.map(c=>`NULL AS \`${c}\``).join(',')} WHERE 1=0`;const wrong=await query(request,'submit',q,q.id===30?'CREATE VIEW country_summary AS '+empty:empty);expect(wrong.ok(),await wrong.text()).toBe(true);expect(await wrong.json()).toMatchObject({accepted:false});});}
test('independent example checks: counts, ties, zero rows, boundaries and no double counting',async({request})=>{async function rows(id){return (await (await request.get(`/api/questions/${id}/example`)).json()).rows}expect(await rows(12)).toEqual([['Aster',3],['United States',3],['Birch',2],['Cedar',2],['Elm',2],['Grove',2],['India',2],['Fir',1],['Dune',0],['Haven',0]]);expect((await rows(14)).filter(r=>r[0]==='Aster')).toEqual([['Aster','Alpha',3000000],['Aster','Beta',3000000]]);expect((await rows(15)).map(r=>r[0])).toEqual(['Cedar','Dune','Elm','Fir','Haven']);expect(await rows(18)).toEqual([['Cedar',4]]);expect(await rows(21)).toEqual([['Europe',602000001]]);expect(await rows(24)).toEqual([[119000000,1027000001,11.59]]);expect((await rows(29)).map(r=>r[0])).toEqual(['Grove','Elm','Aster']);const summaries=await rows(30);expect(summaries.find(r=>r[0]==='Aster')).toEqual(['Aster',10000000,3,3,'Alpha']);expect(summaries.find(r=>r[0]==='Dune')).toEqual(['Dune',2000000,0,0,null]);});
test('SQL lexer accepts comments, decimals, comparisons and literal semicolons',async({request})=>{const sql="-- explain query\nSELECT 'drop; sleep' AS text, 1.25 AS decimal_value, 2 >= 1 AS comparison /* update */; -- trailing comment";const r=await query(request,'run',questions[0],sql);expect(r.ok(),await r.text()).toBe(true);expect((await r.json()).rows).toEqual([['drop; sleep',1.25,1]]);});
test('unsafe SQL, invalid ids, SQL errors and limits have useful errors',async({request})=>{for(const sql of ['SELECT 1; SELECT 2','DELETE FROM city','SELECT SLEEP(1)','SELECT GET_LOCK(\'x\',1)','SELECT * FROM information_schema.tables','SELECT 1 INTO @x','SELECT /*!50000 SLEEP(1) */ 1','SELECT * FROM mysql.user']){const r=await query(request,'run',questions[0],sql);expect(r.status(),sql).toBe(400)}expect((await query(request,'run',{id:999},'SELECT 1')).status()).toBe(404);expect((await query(request,'run',questions[0],'SELECT missing FROM city')).status()).toBe(400);expect((await query(request,'run',questions[0],'SELECT a.ID FROM city a CROSS JOIN city b LIMIT 5001')).status()).toBe(400);expect((await query(request,'run',questions[0],'SELECT 1','invalid')).status()).toBe(400);});
test('alternate correct LEFT JOIN solution accepted; aliases and order enforced',async({request})=>{const q=questions.find(q=>q.id===12);const sql='SELECT c.Name AS CountryName, (SELECT COUNT(*) FROM city ci WHERE ci.CountryCode=c.Code) AS NumberOfCities FROM country c ORDER BY NumberOfCities DESC,CountryName';expect(await (await query(request,'submit',q,sql)).json()).toMatchObject({accepted:true});expect(await (await query(request,'submit',q,sql.replace('DESC','ASC'))).json()).toMatchObject({accepted:false});expect(await (await query(request,'submit',q,sql.replace('AS CountryName','AS WrongName').replace(',CountryName',',WrongName'))).json()).toMatchObject({accepted:false});});
test('fixture connections do not modify the official dataset',async({request})=>{await Promise.all(questions.slice(0,6).map(q=>query(request,'submit',q,solution(q))));expect(await (await request.get('/api/health')).json()).toMatchObject({ok:true,country:239,city:4079,countrylanguage:984});});
test('revealed solutions remain runnable on every dataset',async({request})=>{for(const q of questions){const response=await request.get(`/api/questions/${q.id}/solution`);expect(response.ok()).toBe(true);const {sql}=await response.json();const result=await query(request,'submit',q,sql);expect(result.ok(),await result.text()).toBe(true);expect(await result.json()).toMatchObject({accepted:true,passed:3});}expect((await request.get('/api/questions/999/solution')).status()).toBe(404);});
test('Run compares the selected dataset and includes both complete outputs',async({request})=>{
 const q=questions.find(q=>q.id===12);
 for(const testcase of ['world','example']){
  const correct=await (await query(request,'run',q,q.reference_sql,testcase)).json();expect(correct).toMatchObject({accepted:true,message:'Accepted',passed:1,total:1,testcase});expect(correct.rows).toEqual(correct.expected_rows);expect(correct.columns).toEqual(correct.expected_columns);
  const wrong=await (await query(request,'run',q,'SELECT Name CountryName,0 NumberOfCities FROM country ORDER BY CountryName',testcase)).json();expect(wrong).toMatchObject({accepted:false,message:'Wrong Answer',passed:0,total:1,testcase});expect(wrong.rows).not.toEqual(wrong.expected_rows);expect(wrong.rows).toHaveLength(testcase==='world'?239:10);expect(wrong.expected_rows).toHaveLength(testcase==='world'?239:10);
 }
 const aliases=await (await query(request,'run',q,q.reference_sql.replaceAll('CountryName','WrongAlias'))).json();expect(aliases.accepted).toBe(false);expect(aliases.hint).toContain('aliases');
 const ordered=await (await query(request,'run',q,q.reference_sql.replace(' DESC',' ASC'))).json();expect(ordered.accepted).toBe(false);
});
test('all exercises run accurately on isolated custom data, including CTEs and CREATE VIEW',async({request})=>{
 const ex=await (await request.get('/api/questions/1/example')).json();
 for(const q of questions){const r=await request.post('/api/run',{data:{question_id:q.id,sql:solution(q),testcase:'custom',custom_input:ex.custom_input}});expect(r.ok(),await r.text()).toBe(true);const d=await r.json();expect(d).toMatchObject({accepted:true,passed:1,total:1,testcase:'custom'});expect(d.rows).toEqual(d.expected_rows)}
 expect(await (await request.get('/api/health')).json()).toMatchObject({ok:true,country:239,city:4079,countrylanguage:984});
});
test('custom row edits alter both user and expected output; invalid shapes and keys are rejected',async({request})=>{
 const ex=await (await request.get('/api/questions/12/example')).json();const q=questions.find(q=>q.id===12);const data=structuredClone(ex.custom_input);data.city.rows=[];
 async function custom(d,sql=q.reference_sql){return request.post('/api/run',{data:{question_id:12,sql,testcase:'custom',custom_input:d}})}
 const correct=await (await custom(data)).json();expect(correct.accepted).toBe(true);expect(correct.rows).toHaveLength(10);expect(correct.rows.every(r=>r[1]===0)).toBe(true);
 const duplicate=structuredClone(data);duplicate.country.rows.push(duplicate.country.rows[0]);expect((await custom(duplicate)).status()).toBe(400);
 const wrongWidth=structuredClone(data);wrongWidth.country.rows[0].pop();expect((await custom(wrongWidth)).status()).toBe(400);
 const badType=structuredClone(data);badType.country.rows[0][4]='not a number';expect((await custom(badType)).status()).toBe(400);
 const orphan=structuredClone(data);orphan.city.rows=[[900,'Missing','ZZZ',100,'']];expect((await custom(orphan)).status()).toBe(400);
 const tooMany=structuredClone(data);tooMany.country.rows=Array(101).fill(data.country.rows[0]);expect((await custom(tooMany)).status()).toBe(400);
 const quoted=structuredClone(data);quoted.country.rows[0][1]="O'Reilly; DROP TABLE city; --";expect((await (await custom(quoted)).json()).accepted).toBe(true);
 const missing=await request.post('/api/run',{data:{question_id:12,sql:q.reference_sql,testcase:'custom'}});expect(missing.status()).toBe(400);
});
test('empty outputs and NULL cells are judged accurately',async({request})=>{
 const q=questions.find(q=>q.id===21);const r=await query(request,'run',q,solution(q),'world');expect(await r.json()).toMatchObject({accepted:true,row_count:0,rows:[],expected_rows:[]});
 const summary=questions.find(q=>q.id===30);const d=await (await query(request,'run',summary,solution(summary),'example')).json();expect(d.accepted).toBe(true);expect(d.rows.some(row=>row.includes(null))).toBe(true);
});
test('custom execution supports percent literals and comments before a user CTE',async({request})=>{
 const ex=await (await request.get('/api/questions/12/example')).json();const sql="WITH /* count independently */ counts AS (SELECT CountryCode,COUNT(*) n FROM city GROUP BY CountryCode) SELECT c.Name CountryName,COALESCE(n,0) NumberOfCities FROM country c LEFT JOIN counts ON counts.CountryCode=c.Code WHERE c.Name LIKE '%' ORDER BY NumberOfCities DESC,CountryName";const r=await request.post('/api/run',{data:{question_id:12,sql,testcase:'custom',custom_input:ex.custom_input}});expect(r.ok(),await r.text()).toBe(true);expect(await r.json()).toMatchObject({accepted:true});
});
test('a hidden-case failure includes the actual altered input and an accurate passed count',async({request})=>{
 const q=questions.find(q=>q.id===12);const sql=q.reference_sql.replace('ON c.Code=ci.CountryCode',"ON c.Code=ci.CountryCode AND NOT (c.Code='CCC' AND ci.Population=117)");const r=await query(request,'submit',q,sql);expect(r.ok(),await r.text()).toBe(true);const d=await r.json();expect(d).toMatchObject({accepted:false,passed:2,total:3,testcase:'Hidden edge cases'});expect(d.input.city.rows.some(row=>row[1]==='Cedar Capital'&&row[3]===117)).toBe(true);
});
test('PDF questions 1–10 have independent example checks and meaningful India/California inputs',async({request})=>{
 async function rows(id){return(await(await request.get(`/api/questions/${id}/example`)).json()).rows}
 expect(await rows(1)).toEqual([['Aster'],['Birch'],['India']]);expect(await rows(2)).toEqual([['Los Angeles',5000000],['Mumbai',5000000],['New Delhi',4000000],['Alpha',3000000],['Beta',3000000]]);expect(await rows(3)).toEqual([['French'],['German'],['Italian'],['Spanish']]);expect(await rows(4)).toEqual([['Mumbai',5000000],['New Delhi',4000000]]);expect(await rows(5)).toEqual([['Cedar',600000001],['United States',300000000]]);expect(await rows(6)).toEqual([['Los Angeles'],['San Diego']]);expect(Object.fromEntries(await rows(7))).toEqual({Asia:3,Europe:2,Africa:2,Oceania:2,'North America':1});expect((await rows(8))[0]).toEqual(['Dune',0]);expect(await rows(9)).toEqual([['Birch'],['United States']]);const ex=await(await request.get('/api/questions/10/example')).json();const city=ex.custom_input.city;expect(ex.rows[0][0]).toBe(Math.round(city.rows.reduce((sum,r)=>sum+r[3],0)/city.rows.length*100)/100);
});
