// Author: Prateek Dhall — World Dataset Assignment.
const {test,expect}=require('@playwright/test');
const questions=require('../app/data/questions.json');
const modifier=process.platform==='darwin'?'Meta':'Control';
async function fillEditor(page,value){const input=page.getByRole('textbox',{name:'MySQL query editor'});await input.focus();await input.press(modifier+'+A');await page.keyboard.insertText(value);await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe(value)}
test('complete SQL practice workflow, saving, tabs, history and errors',async({page},testInfo)=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#db')).toContainText('Official dataset');await expect(page.locator('#nav .navitem')).toHaveCount(30);await expect(page.locator('#sidebar')).toBeHidden();await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await expect(page.locator('#description h1')).toContainText('Number of Cities');await page.locator('#schema-tab').click();await expect(page.locator('#schema')).toContainText('CountryCode');await expect(page.locator('#schema')).toContainText('SurfaceArea');await page.locator('#description-tab').click();const sql=questions.find(q=>q.id===12).reference_sql;await fillEditor(page,sql);await page.locator('#testcase').selectOption('world');await page.locator('#run').click();await expect(page.locator('#result')).toContainText('239 rows');await expect(page.locator('#result .your-output table tbody tr')).toHaveCount(50);await page.locator('#result-next').click();await expect(page.locator('#result')).toContainText('51–100');await page.locator('#testcase-tab').click();await page.locator('#testcase').selectOption('example');await page.getByRole('textbox',{name:'MySQL query editor'}).press(process.platform==='darwin'?'Meta+Enter':'Control+Enter');await expect(page.locator('#result')).toContainText('10 rows');await page.locator('#submit').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await expect(page.locator('#progress-label')).toHaveText('1 / 30 solved');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`test-results/${testInfo.project.name}-accepted.png`,fullPage:true});await page.locator('#history-tab').click();await expect(page.locator('#history')).toContainText('Accepted');await page.locator('#history summary').click();await expect(page.locator('#history pre')).toHaveText(sql);await page.reload();await expect(page.locator('#description h1')).toContainText('Number of Cities');await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe(sql);await expect(page.locator('#progress-label')).toHaveText('1 / 30 solved');await fillEditor(page,'SELECT Name AS CountryName, 0 AS NumberOfCities FROM country');await page.locator('#submit').click();await expect(page.locator('#result .status')).toHaveText('Wrong Answer');await expect(page.locator('#result')).toContainText('Expected output');await fillEditor(page,'SELECT broken FROM city');await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('SQL / Runtime Error');await expect(page.locator('#result')).toContainText('Unknown column');expect(errors).toEqual([]);});
test('navigation, filters, reset, theme and accessible narrow-screen layout',async({page},testInfo)=>{await page.goto('/');await expect(page.locator('#nav .navitem')).toHaveCount(30);await page.locator('#toggle-list').click();await page.locator('#search').fill('official');await expect(page.locator('#nav .navitem')).toHaveCount(6);await page.locator('#search').fill('no matching problem xyz');await expect(page.locator('#no-problems')).toBeVisible();await page.locator('#search').fill('');await page.locator('#difficulty').selectOption('Hard');await expect(page.locator('#nav .navitem')).toHaveCount(10);await page.locator('#difficulty').selectOption('');await page.locator('[data-id="30"]').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toMatch(/CREATE VIEW country_summary AS/);await expect(page.locator('#next')).toBeDisabled();await page.locator('#previous').click();await expect(page.locator('#description h1')).toContainText('29.');await fillEditor(page,'SELECT 42');page.once('dialog',d=>d.accept());await page.locator('#reset').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('-- Write your MySQL query statement below\n');await page.locator('#theme').click();await expect(page.locator('body')).toHaveClass(/\blight\b/);await page.reload();await expect(page.locator('body')).toHaveClass(/\blight\b/);await page.locator('#toggle-list').click();await expect(page.locator('#sidebar')).toBeVisible();await page.locator('#close-list').click();await expect(page.locator('#sidebar')).toBeHidden();await expect(page.getByRole('textbox',{name:'MySQL query editor'})).toBeVisible();const size=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`test-results/${testInfo.project.name}-workspace.png`,fullPage:true});});
test('LeetCode workspace tabs, solution reveal, testcase switch and toolbar',async({page},testInfo)=>{
 await page.goto('/');await expect(page.locator('#description h1')).toBeVisible();await expect(page.locator('#sidebar')).toBeHidden();await expect(page.locator('#testcase-content')).toBeVisible();await expect(page.locator('#result')).toBeHidden();await expect(page.locator('#inline-schema')).toContainText('Column Name');
 await page.locator('#inline-schema-toggle').click();await expect(page.locator('#inline-schema')).toBeHidden();await page.locator('#topics-button').click();await expect(page.locator('#topic-detail')).toBeVisible();await page.locator('#editorial-tab').click();await expect(page.locator('#editorial')).toContainText('Approach');await page.locator('#solutions-tab').click();await expect(page.locator('#solution-content')).toBeEmpty();await page.locator('#reveal-solution').click();await expect(page.locator('#solution-content')).toContainText('SELECT');await page.locator('#use-solution').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toContain('SELECT');await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await expect(page.locator('#testcase-content')).toBeHidden();await page.locator('#testcase-tab').click();await expect(page.locator('#testcase-content')).toBeVisible();await page.locator('[data-case="world"]').click();await expect(page.locator('#case-input')).toContainText('239 countries');await page.locator('[data-case="example"]').click();await expect(page.locator('#case-input')).toContainText('country');
 await page.locator('#favorite').click();await expect(page.locator('#favorite')).toHaveAttribute('aria-pressed','true');await page.reload();await expect(page.locator('#favorite')).toHaveAttribute('aria-pressed','true');
 if(testInfo.project.name==='desktop'){await page.locator('#column-resizer').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#column-resizer')).toHaveAttribute('aria-valuenow','52');await page.locator('#row-resizer').focus();await page.keyboard.press('ArrowUp');await expect(page.locator('#row-resizer')).toHaveAttribute('aria-valuenow','33');await page.locator('#timer').click();await expect(page.locator('#timer')).toHaveClass(/running/);await page.locator('#timer').click();await expect(page.locator('#timer')).not.toHaveClass(/running/);}
 await page.locator('#expand-editor').click();await expect(page.locator('.workspace')).toHaveClass(/editor-expanded/);await page.locator('#expand-editor').click();await page.locator('#collapse-results').click();await expect(page.locator('.workspace')).toHaveClass(/results-collapsed/);await page.locator('#collapse-results').click();await page.locator('#description-tab').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`test-results/${testInfo.project.name}-leetcode-layout.png`,fullPage:true});
});
test('questions start at one and existing drafts and progress migrate without collisions',async({page})=>{
 await page.addInitScript(()=>{if(localStorage.getItem('worldsql-numbering-version'))return;localStorage.setItem('worldsql-11','SELECT legacy_first');localStorage.setItem('worldsql-12','SELECT legacy_second');localStorage.setItem('worldsql-21','SELECT legacy_eleventh');localStorage.setItem('worldsql-progress',JSON.stringify({11:true,21:true}));localStorage.setItem('worldsql-current','12');localStorage.setItem('worldsql-favorite-30','true');localStorage.setItem('worldsql-history',JSON.stringify([{id:11,sql:'SELECT legacy_first',date:'2026-10-06T00:00:00Z',accepted:true,status:'Accepted',passed:3,total:3}]))});
 await page.goto('/');await expect(page.locator('#description h1')).toContainText('1. Countries in Asia');await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT legacy_second');await expect(page.locator('#progress-label')).toHaveText('2 / 30 solved');await page.locator('#toggle-list').click();await expect(page.locator('#nav [data-id="11"]')).toContainText('11. Top 3');await expect(page.locator('#nav [data-id="30"]')).toContainText('30. Create a Country Summary');await page.locator('[data-id="11"]').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT legacy_first');await page.locator('#history-tab').click();await expect(page.locator('#history')).toContainText('Accepted');await page.locator('#toggle-list').click();await page.locator('[data-id="21"]').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT legacy_eleventh');await page.reload();await expect(page.locator('#description h1')).toContainText('21. Continents');await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT legacy_eleventh');await expect(page.locator('#progress-label')).toHaveText('2 / 30 solved');
});
test('Run shows green Accepted or red Wrong Answer with output comparison and pagination',async({page},testInfo)=>{
 await page.goto('/');await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await fillEditor(page,questions.find(q=>q.id===12).reference_sql);await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await expect(page.locator('#result .status')).toHaveClass(/accepted/);await expect(page.locator('#result .your-output')).toContainText('10 rows');await expect(page.locator('#result .expected-output')).toContainText('10 rows');await expect(page.locator('#progress-label')).toHaveText('0 / 30 solved');
 await fillEditor(page,'SELECT Name CountryName,0 NumberOfCities FROM country ORDER BY CountryName');await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Wrong Answer');await expect(page.locator('#result .status')).toHaveClass(/wrong/);await expect(page.locator('#result .your-output')).toHaveClass(/output-mismatch/);await expect(page.locator('#result .your-output')).toContainText('0');await expect(page.locator('#result .expected-output')).toContainText('3');
 await page.locator('#testcase-tab').click();await page.locator('#testcase').selectOption('world');await page.locator('#run').click();await expect(page.locator('#result .expected-output')).toContainText('239 rows');await expect(page.locator('#result .your-output table tbody tr')).toHaveCount(50);await expect(page.locator('#result .expected-output table tbody tr')).toHaveCount(50);await page.locator('#expected-next').click();await expect(page.locator('#result .expected-output')).toContainText('51–100');await expect(page.locator('#result .your-output')).toContainText('1–50');await page.locator('#result-next').click();await expect(page.locator('#result .your-output')).toContainText('51–100');await page.locator('#expected-prev').click();await expect(page.locator('#result .expected-output')).toContainText('1–50');await page.screenshot({path:`test-results/${testInfo.project.name}-wrong-answer.png`,fullPage:true});
});
test('custom testcase edits, validation and saved input work without modifying the database',async({page})=>{
 await page.goto('/');await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await page.locator('[data-case="custom"]').click();await expect(page.locator('#case-input')).toContainText('Code · Name · Continent');await page.locator('#custom-city').fill('[]');await fillEditor(page,questions.find(q=>q.id===12).reference_sql);await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await expect(page.locator('#result')).toContainText('Custom testcase');await expect(page.locator('#result .your-output')).toContainText('0');await page.reload();await page.locator('[data-case="custom"]').click();await expect(page.locator('#custom-city')).toHaveValue('[]');await page.locator('#custom-city').fill('not json');await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Invalid Testcase');await expect(page.locator('#result')).toContainText('Invalid JSON in city');await expect(page.locator('#run')).toBeEnabled();await page.locator('#testcase-tab').click();await page.locator('[data-case="example"]').click();await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await expect(page.locator('#result .your-output')).toContainText('3');
});
test('results keep the executed dataset and flag code changes; tabs support keyboard navigation',async({page})=>{
 await page.goto('/');await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await fillEditor(page,questions.find(q=>q.id===12).reference_sql);await page.locator('#run').click();await expect(page.locator('#result')).toContainText('Run · Example dataset');await fillEditor(page,'SELECT 0');await expect(page.locator('#result')).toContainText('Code changed since this result');await page.locator('#testcase-tab').click();await page.locator('[data-case="world"]').click();await page.locator('#testcase-tab').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#result')).toBeVisible();await expect(page.locator('#result')).toContainText('Run · Example dataset');await page.keyboard.press('ArrowLeft');await expect(page.locator('#testcase-content')).toBeVisible();await page.locator('#run').click();await expect(page.locator('#result')).toContainText('Run · Official World dataset');await expect(page.locator('#result')).not.toContainText('Code changed since this result');
});
test('late Run responses cannot overwrite a question after leaving and returning',async({page})=>{
 let release;const gate=new Promise(r=>release=r);await page.route('**/api/run',async route=>{await gate;await route.continue()});await page.goto('/');await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await fillEditor(page,questions.find(q=>q.id===12).reference_sql);await page.locator('#run').click();await expect(page.locator('#run')).toBeDisabled();await page.locator('#next').click();await page.locator('#previous').click();release();await expect(page.locator('#run')).toBeEnabled();await page.locator('#result-tab').click();await expect(page.locator('#result')).toContainText('You must run your code first');await expect(page.locator('#result .status')).toHaveCount(0);
});
test('SQL and network errors release controls and recovery runs succeed',async({page})=>{
 await page.goto('/');await fillEditor(page,'SELECT missing FROM city');await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('SQL / Runtime Error');await expect(page.locator('#run')).toBeEnabled();await page.route('**/api/run',route=>route.abort());await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('SQL / Runtime Error');await expect(page.locator('#submit')).toBeEnabled();await page.unroute('**/api/run');await fillEditor(page,questions[0].reference_sql);await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');
});
test('edited custom inputs are flagged as stale until rerun',async({page})=>{
 await page.goto('/');await page.locator('#toggle-list').click();await page.locator('[data-id="12"]').click();await page.locator('[data-case="custom"]').click();await fillEditor(page,questions.find(q=>q.id===12).reference_sql);await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await page.locator('#testcase-tab').click();await page.locator('#custom-city').fill('[]');await page.locator('#result-tab').click();await expect(page.locator('#result')).toContainText('Testcase changed since this result');await page.locator('#run').click();await expect(page.locator('#result .status')).toHaveText('Accepted');await expect(page.locator('#result')).not.toContainText('Testcase changed since this result');
});
test('failed example submissions show reproducible input and both outputs',async({page})=>{
 await page.goto('/');await page.locator('#toggle-list').click();await page.locator('[data-id="21"]').click();await fillEditor(page,"SELECT Continent,SUM(Population) TotalPopulation FROM country GROUP BY Continent HAVING SUM(Population)>500000000 AND 1=0");await page.locator('#submit').click();await expect(page.locator('#result .status')).toHaveText('Wrong Answer');await expect(page.locator('#result')).toContainText('Failed: Example dataset');await page.locator('.failed-input summary').click();await expect(page.locator('.failed-input')).toContainText('Cedar');await expect(page.locator('#result')).toContainText('Your output (0 rows)');await expect(page.locator('#result')).toContainText('Expected output (1 rows)');
});
test('World Dataset Assignment branding, all 30 questions and Easy filter',async({page},testInfo)=>{
 await page.goto('/');await expect(page).toHaveTitle(/World Dataset Assignment/);await expect(page.locator('#toggle-list')).toContainText('World Dataset Assignment');await expect(page.locator('#description h1')).toHaveText('1. Countries in Asia');await page.locator('#toggle-list').click();await expect(page.locator('#nav .navitem')).toHaveCount(30);await page.locator('#difficulty').selectOption('Easy');await expect(page.locator('#nav .navitem')).toHaveCount(10);await expect(page.locator('#nav [data-id="1"] .diff')).toHaveText('Easy');await page.locator('[data-id="10"]').click();await expect(page.locator('#description h1')).toContainText('10. Average Population');await page.locator('#next').click();await expect(page.locator('#description h1')).toContainText('11. Top 3');await page.locator('#previous').click();await expect(page.locator('#description h1')).toContainText('10. Average Population');await page.screenshot({path:`test-results/${testInfo.project.name}-assignment.png`,fullPage:true});
});
test('interim 1–20 saved work moves to assignment 11–30 exactly once',async({page})=>{
 await page.addInitScript(()=>{if(localStorage.getItem('worldsql-numbering-version'))return;localStorage.setItem('worldsql-numbering-version','2');localStorage.setItem('worldsql-1','SELECT previous_first');localStorage.setItem('worldsql-11','SELECT previous_eleventh');localStorage.setItem('worldsql-progress',JSON.stringify({1:true,11:true}));localStorage.setItem('worldsql-history',JSON.stringify([{id:1,sql:'SELECT previous_first',date:'2026-10-06T00:00:00Z',status:'Accepted',accepted:true}]));localStorage.setItem('worldsql-favorite-20','true')});await page.goto('/');await expect(page.locator('#description h1')).toHaveText('1. Countries in Asia');await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toContain('Write your MySQL');await page.locator('#toggle-list').click();await page.locator('[data-id="11"]').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT previous_first');await page.locator('#history-tab').click();await expect(page.locator('#history')).toContainText('Accepted');await page.locator('#toggle-list').click();await page.locator('[data-id="21"]').click();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT previous_eleventh');await page.reload();await expect.poll(()=>page.evaluate(()=>window.sqlEditor.getValue())).toBe('SELECT previous_eleventh');await expect(page.locator('#progress-label')).toHaveText('2 / 30 solved');
});
