# Author: Prateek Dhall — World Dataset Assignment.
"""Regenerate the MySQL judge seed from app/fixtures.py (no dependencies)."""
import sys
from pathlib import Path
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root))
from app.fixtures import fixture_rows

def literal(value):
    if value is None:return 'NULL'
    if isinstance(value,str):return "'"+value.replace('\\','\\\\').replace("'","''")+"'"
    return str(value)
lines=['-- Author: Prateek Dhall — World Dataset Assignment.', '-- Generated by scripts/build-fixtures.py. Separate read-only judge databases.']
for variant,name in enumerate(('world_example','world_hidden')):
    lines += [f'CREATE DATABASE IF NOT EXISTS `{name}` DEFAULT CHARACTER SET utf8mb4;',f'USE `{name}`;']
    for table,columns,rows in zip(('country','city','countrylanguage'),
        ('Code,Name,Continent,Region,Population,SurfaceArea,Capital','ID,Name,CountryCode,Population,District','CountryCode,Language,IsOfficial,Percentage'),fixture_rows(variant)):
        lines.append(f'CREATE TABLE IF NOT EXISTS `{table}` LIKE `world`.`{table}`;')
        lines.append(f'REPLACE INTO `{table}` ({columns}) VALUES '+',\n'.join('('+','.join(map(literal,r))+')' for r in rows)+';')
(root/'mysql-init/98-fixtures.sql').write_text('\n'.join(lines)+'\n')
